# Dataset configuration
dataset:
  root_dir: "./data/trf/1/thaat"
  labels:
    - "Kalyan (thaat)/Bhoopali"
  train_val_split: 0.9

# Feature extractor configuration
feature_extractor:
  sample_rate: 4000
  n_fft: 256
  hop_length: 32
  n_harmonics: 2
  n_filters_per_semitone: 2

# Backend transformer configuration
backend:
  d_model: 256
  nhead: 8
  num_layers: 4
  dim_feedforward: 256
  dropout: 0.1

# Training configuration
training:
  num_epochs: 450
  learning_rate: 1e-4
  early_stopping_patience: 1000
  project_name: "music-tagging"
  run_name: "hcnn-experiment-Bhoopali"
  logpath: "./logs"
  log_every_n_steps: 10
  save_every_n_epochs: 10
  freeze_fe: true
  dataloader:
    batch_size: 4
    num_workers: 2
    shuffle: false